---
- hosts: all
  tasks:
    - name: Install deb LibSSL 1.1.1 for MongoDB 6+
      apt:
        deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      become: true
      
    - name: Check if MongoDB APT keyring exists
      stat:
        path: /usr/share/keyrings/mongo-key.gpg
      register: mongo_keyring_exists

    - name: Add MongoDB APT keyring
      shell: "curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | sudo gpg --dearmour -o /usr/share/keyrings/mongo-key.gpg"
      args:
        executable: /bin/bash
      when: not mongo_keyring_exists.stat.exists

    - name: Check if MongoDB repository exists
      stat:
        path: /etc/apt/sources.list.d/mongodb-org-6.0.list
      register: mongo_repository_exists

    - name: Add MongoDB repository
      shell: sudo sh -c 'echo deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongo-key.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse > /etc/apt/sources.list.d/mongodb-org-6.0.list'
      args:
        executable: /bin/bash
      when: not mongo_repository_exists.stat.exists

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB packages
      apt:
        name: mongodb-org
        state: latest
    - name: Enable and start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Enable remote connections in MongoDB
      lineinfile:
        path: /etc/mongod.conf
        regexp: "^ *bindIp:.*"
        line: "  bindIp: 0.0.0.0"
        state: present
        backup: yes
      notify:
        - Restart MongoDB Service

    - name: Enable authentication in MongoDB
      lineinfile:
        path: /etc/mongod.conf
        line: "security:\n  authorization: enabled"
        insertafter: "^#security:"
        state: present
        backup: yes
      notify:
        - Restart MongoDB Service
        
  handlers:
    - name: Restart MongoDB Service
      service: name=mongod state=started
